[patch.crates-io.test_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/test_msgs/rust"

[patch.crates-io.type_description_interfaces]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/type_description_interfaces/rust"

[patch.crates-io.std_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/std_msgs/rust"

[patch.crates-io.nav_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/nav_msgs/rust"

[patch.crates-io.action_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/action_msgs/rust"

[patch.crates-io.std_srvs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/std_srvs/rust"

[patch.crates-io.gripper_driver]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/gripper_driver/rust"

[patch.crates-io.sensor_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/sensor_msgs/rust"

[patch.crates-io.trajectory_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/trajectory_msgs/rust"

[patch.crates-io.service_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/service_msgs/rust"

[patch.crates-io.geometry_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/geometry_msgs/rust"

[patch.crates-io.shape_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/shape_msgs/rust"

[patch.crates-io.diagnostic_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/diagnostic_msgs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/rosgraph_msgs/rust"

[patch.crates-io.composition_interfaces]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/composition_interfaces/rust"

[patch.crates-io.statistics_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/statistics_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/unique_identifier_msgs/rust"

[patch.crates-io.lifecycle_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/lifecycle_msgs/rust"

[patch.crates-io.rclrs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/rclrs/rust"

[patch.crates-io.rcl_interfaces]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/rcl_interfaces/rust"

[patch.crates-io.actionlib_msgs]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/actionlib_msgs/rust"

[patch.crates-io.crawler_driver]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/crawler_driver/rust"

[patch.crates-io.builtin_interfaces]
path = "/home/yano/working/rustacean_roborescue/main_ws/install/share/builtin_interfaces/rust"
