[patch.crates-io.service_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/service_msgs/rust"

[patch.crates-io.test_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/test_msgs/rust"

[patch.crates-io.sensor_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/sensor_msgs/rust"

[patch.crates-io.geometry_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/geometry_msgs/rust"

[patch.crates-io.action_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/action_msgs/rust"

[patch.crates-io.rclrs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/rclrs/rust"

[patch.crates-io.example_interfaces]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/example_interfaces/rust"

[patch.crates-io.std_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/std_msgs/rust"

[patch.crates-io.rosgraph_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/rosgraph_msgs/rust"

[patch.crates-io.flipper_driver]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/flipper_driver/rust"

[patch.crates-io.rcl_interfaces]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/rcl_interfaces/rust"

[patch.crates-io.builtin_interfaces]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/builtin_interfaces/rust"

[patch.crates-io.unique_identifier_msgs]
path = "/home/tatsv/working/rustacean_roborescue/main_ws/install/share/unique_identifier_msgs/rust"
