/**:
  ros__parameters:
    common:
      lid_topic: "/velodyne_points"
      imu_topic: "/imu/data"
      time_sync_en: false
      map_frame: "odom" # slam_toolboxにmap->odomを任せる

    preprocess:
      lidar_type: 2 # velodyne lidarは2
      scan_line: 16 # 縦のレーザ本数。vlp-16使うので16
      scan_rate: 10
      timestamp_unit: 2
      blind: 2 # 近距離の無効化距離(m)

    mapping:
      acc_cov: 0.1 # ノイズ共分散。imuよりlidarを信頼したいので、大きめにする予定
      gyr_cov: 0.1
      b_acc_cov: 0.003
      b_gyr_cov: 0.001
      fov_degree: 360.0
      det_range: 100.0
      extrinsic_est_en: false
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]

    filter_size_map: 0.3

    publish:
      path_en: true
      scan_publish_en: true
      dense_publish_en: true
      scan_bodyframe_pub_en: true
